### ISSUE TITLE
Créer un chemin /month pour test éditorial

### ISSUE THREAD

**Issue by adcousin** [geekks/kerlandrier_static#2]
- Filtre # 1 : `oct-24`
- Filtre # 2 : Tous les événements Cap Danse vs un macro-événement Cap Danse (`de xx à xx`)

Pour servir de point de départ aux essais éditoriaux de @pycarnoy

**Comment by JBBailly** [comment]
Pour le filtre #2 on pourrait utiliser les keywords/tags ?
Par exemple attribuer à chaque événement de Cap Danse un tag "Evénement Festival" , et les masquer au print ?

**Comment by adcousin** [comment]
Oui ça paraît pas mal d'utiliser les keywords comme ça on se fait une blacklist.
Si on fait ça, faut qu'on trouve le moyen d'afficher un unique item Cap Danse dans le print.
On va retomber sur le problème "Comment on affiche des événements sur plusieurs jours ?"
